# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20180301_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='conect_us',
            new_name='connect_us',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='descript',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
